# Jekyll config
exclude: [ "README.md" ]
permalink: /posts/:categories/:year/:month/:day/:title:output_ext
paginate: 3
paginate_path: posts/list/:num:output_ext
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
